### ISSUE TITLE
Amend FITS keywords for calibrated L2 data

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/kcor-pipeline#15]
#### Add

+ 'method' or 'technique' keyword for  averaging
+ 'contrast' or some keyword to capture 'nrgf' (`PRODUCT` captures this)

#### Change scaling to units of B/Bsun

- [x] `BSCALE` to 1.  
- [x] Change pipeline. We are currently multiplying by 1000 and saving as 16 bit integers. We want to multiply data by 10^-06 so they are in units of B/Bsun. Data will be saved as floats. Data values should be in range of 10^-6 to 10^-09
- [x] change `BUNIT` keyword value to "B/Bsun"
- [x] gain is in units of 1e-6 B/Bsun, correct for that when applying

#### Fix comment in `BOPAL`

- [x] change from:  " 'Opal Transmission Calibration by Elmore at 775 nm' to: 'Opal Transmission Calib. by Elmore at 775 nm'

#### Wavelength

+ Change `WAVELNTH` keyword (not FITS standard) to `WAVECENT` (leave as `WAVELNTH`)

#### Rsun

- [x] change `RSUN` to `RSUN_OBS` with the same comment
- [x] add `R_SUN` (radius of sun in KCor pixels) = `RSUN_OBS` / `CDELT1`

**Comment by mgalloy** [comment]
For example, DOI.

**Comment by mgalloy** [comment]
Notify Sarah of `BSCALE` change.
