### ISSUE TITLE
Change pipeline to also ship NEW level 1 calibrated data to the HPSS

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/kcor-pipeline#19]
The pipeline currently ships only the level 0 data to the HPSS. Need to tar up and ship level 2 calibrated data as well.

**Comment by mgalloy** [comment]
This will include L1/L1.5 files, averages, and difference images.

This will be in the end-of-day run.

**Comment by mgalloy** [comment]
Released in 1.4.41.
