### ISSUE TITLE
Create additional daily and cumulative engineering and science plots

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/kcor-pipeline#20]
Pipeline currently produces a few daily plots of information: modulator temperature, SGS DIMV, and SGS seeing values. Add software to the pipeline to create additional plots:
1) values of calibrated pB at a fixed height integrated over 360 degrees for each image of the day
2) values of calibrated pB vs. radius for each image of the day
3) create longer time series plots showing average values of modulation matrix, daily pB vs height, daily pB at a fixed height.

**Comment by mgalloy** [comment]
Moving this ticket out of the KCor pipeline, this will be done via the database.
