### ISSUE TITLE
Verify platescale before and after new camera stages

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/kcor-pipeline#21]
We have good alignment of KCor structures in low corona with other data (AIA, CoMP). Need to compare data in outer field with LASCO C2 (and possibly SWAP as well) to verify platescale.
Need to do this with data before and after installation of new camera stages in June 2015.

**Comment by mgalloy** [comment]
@jburkpipe used moon from the 20170821 eclipse to verify to 5.64 arcsec/pixel.
