### ISSUE TITLE
Consistency of L0 directories

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/kcor-pipeline#30]
Prep KCor raw directory.

**Comment by mgalloy** [comment]
Complete through Feb 2015. 

Have confirmed:
* t1 and t2 logs
* data zipped in the level0/ directory
* delete spurious/unexpected directories

**Comment by mgalloy** [comment]
This can be automated in `KCOR_REPROCESS`.

**Comment by jburkepile** [comment]
Finished checking and fixing consistency issues of kcor level0 data from 2013 thru Oct 31 2017 directories. - jb
