### ISSUE TITLE
Check epoch file

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/kcor-pipeline#31]
Make sure `epochs.cfg` is valid for all dates of the mission.

**Comment by mgalloy** [comment]
Need correct calibration for date epochs.

**Comment by mgalloy** [comment]
Need a `PROCESS` boolean to just skip date/time ranges.

**Comment by mgalloy** [comment]
Joan has provided [epoch changes](https://github.com/ncar-mlso/kcor-pipeline/files/1607946/KCOR_EPOCHS-for-processing-software.docx) for the pipeline.

**Comment by mgalloy** [comment]
Still need:

- `raw_filesize` values for length of mission
- new distortion file

**Comment by mgalloy** [comment]
Here is the [latest file for epoch values] for the pipeline from Joan with my annotations. I believe everything is done except the two items mentioned in the comment above.

[latest file for epoch values](https://github.com/ncar-mlso/kcor-pipeline/files/1708686/KCOR_EPOCHS-for-processing-software.docx)

**Comment by mgalloy** [comment]
New distortion file in 8176cc46da6eb60bbb96f7227057744433457746.

**Comment by jburkepile** [comment]
DISTORTION FILES TO USE FOR KCOR MISSION. All times are in Hawaii time (HST). Add 10 hours to get UT.
Epoch date/time                  File to use
Sept. 30, 2013 00:00:00      dist_coeff_20131030_2058.sav
June 19, 2015 00:00:00       dist_coeff_20150630_004337.sav
May 22, 2017 00:00:00       dist_coeff_20170522_205121.sav

Detailed notes on distortion analysis are in the next comment. (jb)

**Comment by mgalloy** [comment]
Released in v1.4.41.
