### ISSUE TITLE
Incorrect LUTs applied in early mission

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/kcor-pipeline#34]
Need an epoch value to apply correction for incorrect LUTs in the early mission.

**Comment by mgalloy** [comment]
Need lookup tables (from @dwijn) for early mission dates (from @jburkepile).

**Comment by jburkepile** [comment]
Joan completed a timeline history of all LUTs applied to all cameras. An excel spread sheet titled 'KCOR_LUT_camera_expsoure_history.xlsx' contains for all exposure changes and includes FITS header info; including header information that was incorrect in the level0 data (in excel spread SHEET 1). Sheet 2 contains the list of camera corrections needed from Alfred to reprocess the mission. Mike has uploaded this excel spread sheet on the [KCor instrument history wiki page](https://github.com/ncar-mlso/kcor-pipeline/wiki/KCor-instrument-history).
