### ISSUE TITLE
Average daily good image

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/kcor-pipeline#36]
Create average of good images for the day.

**Comment by mgalloy** [comment]
This could be done in the real-time run. There will be a time threshold (12-15 minutes) and a minimum number of images.

**Comment by jburkepile** [comment]
1) Need to use this as the filename format for the daily average image:
yyyymmdd_hhmmss_kcor_l1_dailyavg.fts
yyyymmdd_hhmmss_kcor_l1_dailyavg.gif
yyyymmdd_hhmmss_kcor_l1_dailyavg_cropped.gif

2) Need to generate a daily nrgf fts / gif / cropped gif from the daily avg fts. and use these filenames:
yyyymmdd_hhmmss_kcor_l1_nrgf_dailyavg.fts
yyyymmdd_hhmmss_kcor_l1_nrgf_dailyavg.gif
yyyymmdd_hhmmss_kcor_l1_nrgf_dailyavg_cropped.gif

**Comment by mgalloy** [comment]
This is currently implemented as an extended average, `extavg`.
