### ISSUE TITLE
2 minute average and replace NRGF with 2 minute average NRGF

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/kcor-pipeline#43]
In the end-of-day processing, create a two minute average at the same times NRGF images are created. Also, replace existing NRGFs with an NRGF of the two minute average files. Create FITS and fullres/lowres GIFs for each of these files.

#### Steps

- [x] create two minute average FITS and fullres/lowres GIFs
- [x] create daily average FITS and fullres/lowres GIFs
- [x] distribute average FITS and GIF files
- [x] add the average files to the `kcor_img` table?
- [x] set `num_kcor_pb_avg_fits`, `num_kcor_pb_dailyavg_fits`, `num_kcor_pb_avg_lowresgif`, and `num_kcor_pb_avg_fullresgif` fields of `mlso_numfiles` table
- [x] delete existing NRGF FITS/GIF files in `level1`, `archive`, `fullres`, and `cropped` directories
- [x] delete existing NRGF files, i.e., `producttype = 'nrgf'`, in `kcor_img` table
- [x] create a new NRGF file corresponding to each average file, including the daily average
- [x] distribute new averaged NRGF FITS and GIF files
- [x] add the new averaged NRGF files to the `kcor_img` table
- [x] correct `num_kcor_nrgf_fits`, `num_kcor_nrgf_lowresgif`, `num_kcor_nrgf_fullresgif`, and `num_kcor_nrgf_dailyavg_fits` entries in the `mlso_numfiles` table of the database

**Comment by mgalloy** [comment]
### Database

- Need to delete NRGF images in `kcor_img1 table of the database. Delete everything for the observing day with `producttype = 'nrgf'`.
- Update `mlso_numfiles` for the `num_kcor_nrgf_fits`, `num_kcor_nrgf_lowresgif`, `num_kcor_nrgf_fullresgif` columns

### `KCOR_NRGF`

- Should also change the `LEVEL` FITS keyword from "L1NRGF" to "L1".
- Add keyword `PRODUCT` with value `NRGF` during the realtime and `NRGFAVG` in the eod.

**Comment by kolinski** [comment]
Added new fields to mlso_numfiles:
num_kcor_pb_avg_fits
num_kcor_pb_dailyavg_fits
num_kcor_pb_avg_lowresgif
num_kcor_pb_avg_fullresgif
num_kcor_nrgf_dailyavg_fits

Since the NRGF realtime files will be replaced at end of day, only one new entry for the daily average was added for this type.

**Comment by jburkepile** [comment]
Here is the filename format to use for the 2-min average images:
yyyymmdd_hhmmss_kcor_l1_avg.fts
yyyymmdd_hhmmss_kcor_l1_avg.gif
yyyymmdd_hhmmss_kcor_l1_avg_cropped.gif

**Comment by mgalloy** [comment]
To make production database ready for release, need to add "nrgfavg", "pbavg", "pbdailyavg", and "nrgfdailyavg" product types to the `mlso_producttype` table.

**Comment by mgalloy** [comment]
05dd8ef08fbdc2181d22a1e852a2d525bad1030b makes, distributes, and adds daily NRGFs to the database.
