### ISSUE TITLE
Use bad fit mask from camera correction file

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/kcor-pipeline#59]
There is a mask of pixels which don't have a good fit from the camera correction. The values for these pixels should be interpolated from neighboring pixels at the time of the distortion correction.

Separate bad pixel mask into first/last column and individual points. Correct individual points by interpolating using nearest neighbor, 3x3. Correct first/last columns by using median of row from occur edge to the bad columns. Should need to do this per camera.

**Comment by mgalloy** [comment]
Examining the locations of the individual bad pixels (not leading and trailing columns) against example images doesn't show observable defects. @jburkepile believes the bad values are subtracting out. The bad columns are masked out in the final product.

`KCOR_READ_CAMERA_CORRECTION` still has capability to read the bad pixel mask and pull out the bad columns and individual values, but closing ticket for now.

**Comment by dwijn** [comment]
It's nice to know the resulting images do not show observable defects. I did calibrate the pixels in the bad pixel mask; I just don't consider the result trustworthy. To some extent the bad values will subtract out, but the camera calibration probably does the bulk of the work. Easy to check by taking a look at data prior to demodulation but after camera correction. Even if they are not detectable by eye, these pixels will have substantially higher random noise than other pixels. So I suspect that a more in-depth investigation would reveal them, but if we can't see them I think it's fine to ignore them for now.

**Comment by jburkepile** [comment]
I did not distortion correct the bad pixel mask to determine exactly where they land in the processed images but a visible inspection on the area zoomed by a factor of 8 didn't reveal anything qualitative. I am sure, as you say, if we look in-depth we'll see some residual signature. Given the much larger issues (e.g. fringing) that exercise is in the noise. Literally.
cheers!
