### ISSUE TITLE
Change non-averaged GIF names and cropped GIF annotation 

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/kcor-pipeline#63]
1. Filename changes: add "l1" to names
  - fullres filename: `yyyymmdd_hhmmss_kcor_l1.gif`
  - new lowres (cropped) filename: `yyyymmdd_hhmmss_kcor_l1_cropped.gif`

2. Annotation changes to cropped GIFs:  same changes to lowres GIFs as described in #43 except leave out "2 min. avg" annotation in the lower right corner of the image

**Comment by mgalloy** [comment]
Fullres and lowres filenames changed in 497b5ff29c7ca768f7d6ab8249535718421d3b50.
