### ISSUE TITLE
Improve GIF scaling and color table

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/kcor-pipeline#66]
Modify color table and gamma to avoid contrast loss in the inner corona.

**Comment by jburkepile** [comment]
Replace lowres gif with full res inner FOV keeping gif size 512 x 512
Use B/W color table (loadct,0)
use default gamma = 1
**TBD TESTING : EXP = .7  MIN = 0, MAX .7  (for 2017)**
draw circle at photosphere
Change annotation: 
a) remove east, north, west labels
b) remove K-Coronagraph label in upper left
c) put date / time on topmost line 
d) put min/max, scaling on one line on bottom
e) remove gamma = .065 from bottom
f) remove 2 min. avg and Circle = photosphere labels in bottom right.

**Comment by mgalloy** [comment]
Old cropped GIF:

![kcor-cropped-gif-old](https://user-images.githubusercontent.com/713524/39596126-abbcb42c-4ece-11e8-8e34-06af01931e88.png)

New cropped GIF:

![kcor-cropped-gif](https://user-images.githubusercontent.com/713524/39596059-7e4b5318-4ece-11e8-95f0-9d6a72a5d8ab.png)

**Comment by mgalloy** [comment]
And with the new scaling:

![kcor-cropped-gif-newscaling](https://user-images.githubusercontent.com/713524/39598404-abe208d8-4ed5-11e8-8c07-29a69a315b2b.png)

**Comment by mgalloy** [comment]
Released in v1.4.41.

**Comment by mgalloy** [comment]
Need to do the new cropped GIF changes for the extended average as well.

**Comment by mgalloy** [comment]
Change:

- [ ] change format statement for all (non-NRGF) min/max values annotations
- [ ] color table for L1 fullres should be the predefined table 0, i.e., `loadct, 0`
- [x] gamma for L1 fullres should be 0.6

**Comment by mgalloy** [comment]
Difference GIF images need to be fixed the same way the regular GIFs were:

- [ ] multiply by 1e6 when displaying
- [ ] min/max annotations need fixed, i.e., -2.0e-08 to 2.0e-08
