### ISSUE TITLE
Occulter size wrong in FITS header

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/kcor-pipeline#86]
The occulter size is reported incorrectly in KCor level 0 FITS headers between May 4, 2018 (start of day) and Sept 26 2018 23:51 UT [i.e. 13:51 HST].  

It is reported as `OC-1006.9"`. It should be `OC-991.6"`

Need to create an epoch in pipeline to fix this in the level 1.5 headers.

**Comment by mgalloy** [comment]
Need to reprocess a day in this epoch.

**Comment by mgalloy** [comment]
Run on 20180728 and was working.
